#!/usr/bin/env bash
#
# link dotfiles

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

install_dotfiles () {
  echo 'installing dotfiles'
  echo "from $DOTFILES_ROOT"

  rm $HOME/.zshrc && ln -s $DOTFILES_ROOT/zsh/zshrc-saw $HOME/.zshrc
  rm $HOME/.zpreztorc && ln -s $DOTFILES_ROOT/zsh/zpreztorc-saw $HOME/.zpreztorc
  rm $HOME/.p10k.zsh && ln -s $DOTFILES_ROOT/zsh/p10k.zsh-saw $HOME/.p10k.zsh
}

install_dotfiles
